### ISSUE TITLE
[Enhancement]: See how many chapters are in the selected title

### ISSUE THREAD

**Issue by PassiveLemon** [C9Glax/tranga-website#110]
Just a nice way to see how many chapters will get downloaded without having to actually start the job.

Very crude example:
![image](https://github.com/user-attachments/assets/9b7c64be-e26d-4521-9b8f-e51f9b13a97f)

**Comment by db-2001** [comment]
This is already planned implemented on the website side V2 branch though the API still seems to be reporting 0, gonna close this issue
