### ISSUE TITLE
Loading a blank empty Page

### ISSUE THREAD

**Issue by MonkeyDrone** [C9Glax/tranga-website#131]
Tranga-Website has started to just load a blank empty page now. It was working fine earlier.

This is what Tranga-Website log shows when the URL is opened in the browser. I've tried Firefox, Google Chrome and Google Chrome in mobile as well. All blank screens.

---
     

192.168.100.23 - - [19/Oct/2024:16:32:25 +0000] "GET / HTTP/1.1" 200 313 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0" "-"

192.168.100.23 - - [19/Oct/2024:16:32:25 +0000] "GET /styles/index.css HTTP/1.1" 200 611 "http://192.168.100.249:9555/" "Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0" "-"

192.168.100.23 - - [19/Oct/2024:16:32:25 +0000] "GET /index.jsx HTTP/1.1" 200 207 "http://192.168.100.249:9555/" "Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0" "-"

2024/10/19 16:32:26 [error] 31#31: *36 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.100.23, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.100.249:9555", referrer: "http://192.168.100.249:9555/"

192.168.100.23 - - [19/Oct/2024:16:32:26 +0000] "GET /favicon.ico HTTP/1.1" 404 153 "http://192.168.100.249:9555/" "Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0" "-"

---

**Comment by C9Glax** [comment]
Check [here](https://github.com/C9Glax/tranga/issues/266) just pull latest again.
