### ISSUE TITLE
Adding Kavita login details has no effect

### ISSUE THREAD

**Issue by Jacksaur** [C9Glax/tranga-website#19]
Managed to add the API-URI of Tranga, and Gotify, but I can't seem to add my login details for Kavita at all.
I enter the same URL as I use to access Kavita, followed by my main account's username and password. Hit enter, all fields clear, configured icon still shows as no.  
I've tried both just hitting enter and using the update button. Checked several times, copied the URL directly from when I was accessing Kavita and triple checked my login details, everything's correct.

I'd provide logs, but I can't seem to find any?

**Comment by db-2001** [comment]
I also noticed this behavior, I'll be helping out with some of the website stuff so I'll look into it, but I think the source of the error is something on the tranga-api side which @C9Glax will have to take care of for now

**Comment by C9Glax** [comment]
Hey there,
to get logs run `docker logs tranga-api`. Without that I can't even speculate sadly...

**Comment by Jacksaur** [comment]
No change in logs whenever I hit enter. I retried my Gotify details, and that gives an expected "Creating notification connector Gotify", followed by adding Gotify, followed by "Exporting notification connectors".

I entered false info into the Komga fields, and when I pressed enter that still at least gave a "Creating library connector Komga" before going silent. It seems my Kavita details aren't being submitted at all, perhaps?

**Comment by C9Glax** [comment]
Okay pressing enter doesn't even send a request to the api...

**Comment by C9Glax** [comment]
No what I meant is that for me no request was going out.
However I noticed that there was a parameter missing in the url...
And that if object/connector creation failed, it wouldn't even output anything to log.

Could you try now?

**Comment by Jacksaur** [comment]
That got it saved:
Took me a while to ensure the update fully applied, still learning the intracicies of Docker, apologies. Adding the server details and hitting enter populated the log and now shows a success sign under the Kavita listing, with the IP remaining in place. Also persists after a full container restart.

By testing a Manga though, it failed to update Kavita. Watching the logs, it seems Port number is not saved on entry?
`[10/30/2023 18:03:07.0  ]     NetClient | GET http://192.168.0.8/api/Library -> 404: Not Found`

My address for Kavita is 192.168.0.8:5000. No Gotify notifications are going through either, and that's on port 8070. Going off the assumption that the greyed out text is an exact representation of what's saved: [It seems only the Tranga API URI actually has its port number saved currently](https://i.imgur.com/2qNU1mN.png).

**Comment by C9Glax** [comment]
I run everything through a reverse proxy on subdomains, so I guess those get cut-off...
Shouldn't be too hard to fix

**Comment by C9Glax** [comment]
Okay quick question: Does it show the port when first creating the connector, and only after restart it disappears?

**Comment by Jacksaur** [comment]
Disappears from the field the instant I hit enter, in the logs it shows as being added without Port number as well.

**Comment by C9Glax** [comment]
When build is done it should work, had a wrong Regex setup on the api, that would filter out ports

**Comment by Jacksaur** [comment]
Argh, so close now!
Ports save, Gotify alerted just fine, that side is all dealt with. I tried to replace Kavita's IP with one that included the port number and encountered the same issue of it not saving yet again.
Presuming it was related to overwriting the value, I stopped the container, manually deleted the libraryConnectors.json file, and then tried to add through the Web UI again once the container was back up. No dice, we're back to the first issue where the Kavita fields have zero effect. All other fields trigger output in the logs as expected.

Thank you for the swift support with all this, by the way.

**Comment by C9Glax** [comment]
Yea somewhere along the way it reverted https://github.com/C9Glax/tranga-website/commit/0b09df67b9c3252ef087bffba4cde050ac736ca8 could you clear your cache and try again?

**Comment by db-2001** [comment]
Prune gets rid of images you're not using (i.e. old ones) and restarting is just restarting. If you're using portainer to manage containers (I would recommend it). You can from the interface, recreate: 

![image](https://github.com/C9Glax/tranga-website/assets/125827669/deb3c499-72c5-47fc-ab1d-6524fb48773e)

And make sure you toggle the switch to pull the latest image: 

![image](https://github.com/C9Glax/tranga-website/assets/125827669/2c9c6389-03ff-4608-be77-3b1aca449e76)

If you're using docker compose, then a simple `docker compose down` and then `docker compose up -d` in the command line will automatically pull the latest image

**Comment by Jacksaur** [comment]
Recreated through Portainer, and did a docker compose pull for good measure, still the same issue I'm afraid.

**Comment by C9Glax** [comment]
Okay for me it's working, however the settings say that is isn't configured until 1/2 seconds later **and a refresh.**
That is because the api is still busy getting the token from kavita, and thus not fully created yet, when the website already is trying to fetch the new settings.

**Comment by C9Glax** [comment]
The 200 indicates that Kavita has accepted the request, maybe it's a staggered scan, and the repeated trigger interrupts the previous one? idk, seems to be a Kavita issue

**Comment by Jacksaur** [comment]
Fair enough, I'll take it up with the Kavita author.

Worst case scenario: I can delete and remake my libraries to have my Manga occupy ID 1 instead.
Thanks for all the effort you've put in here: This software is going to make my roommate very happy.
