### ISSUE TITLE
Hover style breaking release-status

### ISSUE THREAD

**Issue by C9Glax** [C9Glax/tranga-website#29]
@db-2001 
![grafik](https://github.com/C9Glax/tranga-website/assets/13404778/165c543d-d53e-4808-bbf9-07ad8bfd1601)
When using your hover style, the releaseStatus-indicator breaks.

Also I was thinking, that it might be better to have it in a static location, for example in the top right corner, instead of behind the name?

**Comment by db-2001** [comment]
Hm, thought I fixed the first issue with it breaking, I'll double check. Yeah I was going back and forth between static location and next to the name, would you want the indicator to be always visible even with the hover style (like the chapter count would)?

**Comment by C9Glax** [comment]
Your choice really :)
For consistency just keep it visible?

**Comment by db-2001** [comment]
![image](https://github.com/C9Glax/tranga-website/assets/125827669/8a1cafca-d392-4401-bdac-3b9634158704)
Looks like it works for me, could be one of those pesky cache issues

**Comment by db-2001** [comment]
If you can confirm that the CSS being weird on hover is just a page cache thing then this issue is resolved with #32

**Comment by C9Glax** [comment]
Works for me!
You can hard-refresh with ctrl+F5
