### ISSUE TITLE
Add an UpdateMetadata button

### ISSUE THREAD

**Issue by C9Glax** [C9Glax/tranga-website#30]
@db-2001 
https://github.com/C9Glax/tranga-website/pull/27#issuecomment-1790682893
API-Side is working
https://github.com/C9Glax/tranga/issues/79

**Comment by db-2001** [comment]
Going to break this one into two, one pull request for reworking the settings pop-up and one for reworking the manga pop-up

**Comment by db-2001** [comment]
#33 Settings page

**Comment by db-2001** [comment]
Existing issue exists specifically for manga pop up
