### ISSUE TITLE
Volume mounting in compose

### ISSUE THREAD

**Issue by m8dotpie** [C9Glax/tranga-website#36]
Docker compose volumes have incorrect paths
`- ./tranga:/usr/share/Tranga-API` in tranga-api
Should be:
`- ./tranga:/usr/share/tranga-api`
Since the working dir in the container is all lowercase letters.
Anyway I am not sure why it is needed to mount volumes in the first place? To have the common cache between website and api? It works either way, just take into consideration the paths if you want to mount properly.

**Comment by C9Glax** [comment]
Yup actually there shouldn't be a docker-compose in this repo at all!

**Comment by m8dotpie** [comment]
> Yup actually there shouldn't be a docker-compose in this repo at all!

Just keep in mind, that README.md pointed at this file and there is no valid installation instructions right now
