### ISSUE TITLE
Custom RateLimit setting

### ISSUE THREAD

**Issue by C9Glax** [C9Glax/tranga-website#39]
@db-2001 Hey do you have any ideas on how to design this?
https://github.com/C9Glax/tranga/issues/109

Right now requestLimits (apart from MangaDex which is very strict) use byte 1 and a value of 1 request per second.
[API is already done](
https://github.com/C9Glax/tranga/blob/c706824222f8cc76afca25ebc05a9e2efc360a39/Tranga/Server.cs#L399).
Already did the UserAgent as that was Straightforward enough, but am kinda stumped on how I want to do this.

**Comment by db-2001** [comment]
I'm a little bit lost on what youre asking. Are you asking do I have a way to design the front end to allow for custom user agents and rate limits per site? Or how to actually implement the rate limiting? For the former, yes I have an idea. I wanted to put all the connectors in a section on the settings page so that eventually when global search is enabled, you could disable connectors you didn't want to search, these settings could just go there. For the latter, I don't have any offhand knowledge about rate limiting but I could look into it?

**Comment by C9Glax** [comment]
Oh I was asking about the design yes.
The API is already done and (hopefully) working, it's just a frontend thing.
The global search thing sounds cool and putting in the ratelimits there sounds like a good idea 👍🏼 

> Could you also clarify what you mean by requestType in the API? I'm not sure what/how the byte 1 you mentioned is being used.

I was trying to explain how it works at the moment. Different requesttypes (e.g. a website, an author-information, an image) have different bytevalues. I think only Mangadex has that though and all others just use a bytevalue of 1. thats what i meant

**Comment by db-2001** [comment]
Ah okay, I think I get it. I'll try and mock up something and put in a pull request sometime this weekend. Couple questions, does the bytevalue need to be handled on the front-end side? If so what do the different bytevalue for MDex correspond to? Second question, should the global search be implemented on the front-end side or server side, I can do it pretty easily on the front end side but, I feel like storing which connectors are enabled/disabled should be handled by the API.

**Comment by C9Glax** [comment]
> Couple questions, does the bytevalue need to be handled on the front-end side

Kind of, if you want to configure a specific request rate limit then yes. The bytevalues are in every constrcutor, for example [here](https://github.com/C9Glax/tranga/blob/c706824222f8cc76afca25ebc05a9e2efc360a39/Tranga/MangaConnectors/MangaDex.cs#L21).

> I feel like storing which connectors are enabled/disabled should be handled by the API.

Yea this would also fall in line with disabling connectors if chrome fails.

So I guess should be implemented on api side...

**Comment by db-2001** [comment]
Can you add GET API calls to populate the value of the textbox with the saved rate limit
