### ISSUE TITLE
Docker-Compose missing?

### ISSUE THREAD

**Issue by yacob841** [C9Glax/tranga-website#42]
When attempting to download the docker-compose.yaml I’m getting a 404 error and I am not seeing the docker compose file in the GitHub.

**Comment by db-2001** [comment]
The docker-compose.yaml is over in the main API repository. It includes the website container.

**Comment by yacob841** [comment]
Got it, ty! I found this because I have Kaizoku but from what I can tell it looks like it’s not being maintained (been a long time since the last update or comment). I hope you don’t mind but I plan on making quite a few feature requests lol.

**Comment by db-2001** [comment]
Yeah, that was @C9Glax's main reason for creating this project. Feature requests are good lol, I'm working primarily on the web front-end and have quite a few things planned myself. C9Glax handles the API side by themselves for now so any feature requests that relate to how the backend behaves should be made over there on that repo.
