### ISSUE TITLE
Multi-site search

### ISSUE THREAD

**Issue by yacob841** [C9Glax/tranga-website#43]
Since I normally don’t know which site has the manga I’m looking for this causes me to go one at a time and search through each site until I find the one I need. I think it will be useful if we could do a multi-site or all site search. Basically you type in the name and then it searches all sites and shows the results for all sites.

**Comment by db-2001** [comment]
This is a feature that is already planned to be implemented on the API side, website will not be handling global search.

**Comment by yacob841** [comment]
Sounds good! Ty!
