### ISSUE TITLE
API-URI Error when using reverse proxy

### ISSUE THREAD

**Issue by yacob841** [C9Glax/tranga-website#53]
I am using NPM and Authentik causing my URL to become https://domain.tld. After settings this if I access tranga-web using ip and port then it works but if I use domain.tld I get an error stating "Check your Settings > API-URI" when I view that it shows a greyed out "https://" I attempt to put "https://domain.tld" but after pressing update it disappears and the issue remains. Any ideas on how to resolve this?

**Comment by db-2001** [comment]
Just to be clear, you understand that the URI should be the url of the tranga-api which should be different from the url of the front-end right? From your description it seems like you're trying to access both services from the same link which just won't work.

**Comment by yacob841** [comment]
Yeah, I realized that after the fact but even when I put the tranga-api url it doesn’t work as long as I’m accessing tranga using reverse proxy. I’ll try messing with it some more.On Feb 13, 2024, at 7:10 PM, Dity ***@***.***> wrote:﻿
Just to be clear, you understand that the URI should be the url of the tranga-api which should be different from the url of the front-end right? From your description it seems like you're trying to access both services from the same link which just won't work.

**Comment by db-2001** [comment]
The issue could also be HTTPS. The front-end makes HTTP requests currently so any HTTPS server will block those by default. HTTPS is something that is on our radar. The main repository has some issues (might be closed) over there that may be of help.

**Comment by balgerion** [comment]
Anyone found solution for that ?  tranga website is expecting https when behind nginx 
![{F04DF433-3833-4E51-BE1B-C700B4C6B824}](https://github.com/user-attachments/assets/e67a38ee-7025-49ef-9965-2a4108a7c0ee)

**Comment by C9Glax** [comment]
You also have to reverse proxy the API on Port 6531 with https.
You can't make http requests from a https site.
